<#
.SYNOPSIS
    Builds the single-file release of Klaudik WinKit.

.DESCRIPTION
    Produces, in ./dist:
      WinKit.ps1         the complete app (sources + embedded config and XAML)
      WinKit.ps1.sha256  its SHA-256 checksum
      win.ps1            the launcher served at https://klaudik.com/win,
                         pinned to this exact build's checksum

    The build is deterministic: the same sources always produce the same
    bytes and therefore the same checksum.
#>
[CmdletBinding()]
param(
    # Defaults to dist\ next to this script.
    [string]$Output,
    [string]$Repository = 'klaudikdev/winkit'
)

$ErrorActionPreference = 'Stop'
# $PSScriptRoot can be empty in Windows PowerShell 5.1 when started with -File.
$root = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $Output) { $Output = Join-Path $root 'dist' }
$version = (Get-Content -LiteralPath (Join-Path $root 'VERSION') -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') { throw "VERSION must be semantic (x.y.z), got '$version'." }

function Read-Source([string]$RelativePath) {
    $text = [System.IO.File]::ReadAllText((Join-Path $root $RelativePath), [System.Text.Encoding]::UTF8)
    return ($text -replace "`r`n", "`n").TrimEnd() + "`n"
}

function Test-Ascii([string]$Name, [string]$Text) {
    # Windows PowerShell reads scripts in the system code page unless they
    # have a BOM; keeping sources ASCII makes that irrelevant.
    $bad = [regex]::Match($Text, '[^\x09\x0A\x0D\x20-\x7E]')
    if ($bad.Success) {
        $line = ($Text.Substring(0, $bad.Index) -split "`n").Count
        throw "$Name contains a non-ASCII character on line $line. Use an escape instead."
    }
}

$resources = @(
    'VERSION',
    'config/tweaks.json',
    'config/profiles.json',
    'config/apps.json',
    'config/network.json',
    'config/developer.json',
    'src/ui/MainWindow.xaml'
)

$sources = @()
foreach ($folder in 'src/core', 'src/modules', 'src/ui', 'src/ui/Pages') {
    $sources += Get-ChildItem -LiteralPath (Join-Path $root $folder) -Filter '*.ps1' | Sort-Object Name -Culture '' |
                ForEach-Object { "$folder/$($_.Name)" }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.Append(@"
<#
    Klaudik WinKit $version
    An open-source toolkit for setting up and tuning Windows 10 and 11.

    https://klaudik.com
    https://github.com/$Repository

    Copyright (c) Klaudik. Released under the MIT License.

    This file is generated by build.ps1 from the sources in the repository.
    Do not edit it directly.
#>
[CmdletBinding()]
param(
    [switch]`$Preview
)

`$script:WKScriptPath = `$PSCommandPath
# Keep the text of the code that is running so elevation relaunches exactly
# this code rather than whatever is on disk by then. Under Invoke-Expression
# MyInvocation describes the caller instead, so only accept text that is
# recognizably this file.
`$script:WKScriptText = `$null
if (`$MyInvocation.MyCommand.ScriptBlock) {
    `$wkSelf = `$MyInvocation.MyCommand.ScriptBlock.ToString()
    if (`$wkSelf.Contains('WKEmbedded[' + "'config/tweaks.json']")) { `$script:WKScriptText = `$wkSelf }
    # No cmdlets before Start-WinKit locks down the module path.
    `$wkSelf = `$null
}
`$script:WKRoot = `$null
`$script:WKEmbedded = @{}

"@.Replace("`r`n", "`n"))

foreach ($r in $resources) {
    $content = Read-Source $r
    Test-Ascii $r $content
    if ($content -match "(?m)^'@") { throw "$r contains a line starting with '@ and cannot be embedded." }
    [void]$sb.Append("`$script:WKEmbedded['$r'] = @'`n$content'@`n`n")
}

foreach ($s in $sources) {
    $content = Read-Source $s
    Test-Ascii $s $content
    [void]$sb.Append("#region $s`n$content#endregion`n`n")
}

[void]$sb.Append("Start-WinKit @PSBoundParameters`n")

$text = $sb.ToString().Replace("`n", "`r`n")

# Refuse to ship a script that does not parse.
$tokens = $null
$errors = $null
[void][System.Management.Automation.Language.Parser]::ParseInput($text, [ref]$tokens, [ref]$errors)
if ($errors) { throw "Build output does not parse: $($errors[0].Message) at line $($errors[0].Extent.StartLineNumber)" }

if (-not (Test-Path -LiteralPath $Output)) { New-Item -ItemType Directory -Path $Output | Out-Null }
$appPath = Join-Path $Output 'WinKit.ps1'
[System.IO.File]::WriteAllText($appPath, $text, (New-Object System.Text.UTF8Encoding $true))

$hash = (Get-FileHash -LiteralPath $appPath -Algorithm SHA256).Hash
[System.IO.File]::WriteAllText("$appPath.sha256", "$hash  WinKit.ps1`n", (New-Object System.Text.UTF8Encoding $false))

$launcher = Read-Source 'templates/launcher.ps1'
$launcher = $launcher.Replace('{{VERSION}}', $version).Replace('{{SHA256}}', $hash).Replace('{{REPOSITORY}}', $Repository)
Test-Ascii 'launcher' $launcher
[System.IO.File]::WriteAllText((Join-Path $Output 'win.ps1'), $launcher.Replace("`n", "`r`n"), (New-Object System.Text.UTF8Encoding $false))

Write-Host "Built Klaudik WinKit $version" -ForegroundColor Green
Write-Host "  $appPath ($([math]::Round((Get-Item $appPath).Length / 1KB)) KB)"
Write-Host "  SHA-256 $hash"
Write-Host "  $(Join-Path $Output 'win.ps1')"
