# Shareable system report (self-contained HTML, no external resources).

function ConvertTo-WKHtml {
    [CmdletBinding()]
    param([AllowNull()][AllowEmptyString()][string]$Text)
    if ($null -eq $Text) { return '' }
    return [System.Net.WebUtility]::HtmlEncode($Text)
}

function Export-WKReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]$Health,
        [Parameter(Mandatory)][string]$Path
    )

    $s = $Health.System
    $e = { param($t) ConvertTo-WKHtml $t }
    # The report is in English, so are its dates.
    $en = [System.Globalization.CultureInfo]::GetCultureInfo('en-US')

    $rows = @(
        @('Windows', "$($s.OS) $($s.Version)"),
        @('Device', "$($s.Manufacturer) $($s.Model)"),
        @('Processor', "$($s.Cpu) ($($s.Cores))"),
        @('Memory', (Format-WKBytes $s.MemoryBytes)),
        @('Graphics', $s.Gpu),
        @('System drive', "$(Format-WKBytes $s.DiskFreeBytes) free of $(Format-WKBytes $s.DiskSizeBytes)")
    ) | ForEach-Object { "<tr><th>$(& $e $_[0])</th><td>$(& $e $_[1])</td></tr>" }

    $checks = foreach ($c in $Health.Checks) {
        $cls = $c.Status.ToLowerInvariant()
        "<li class=""$cls""><span class=""dot""></span><div><strong>$(& $e $c.Title)</strong><p>$(& $e $c.Detail)</p></div><em>$(& $e $c.Status)</em></li>"
    }

    $active = @(Get-WKActiveHistory)
    $changes = if ($active.Count) {
        ($active | Select-Object -First 30 | ForEach-Object {
            "<li><span>$(& $e ([datetime]$_.time).ToString('g', $en))</span>$(& $e $_.title)</li>"
        }) -join ''
    }
    else { '<li class="empty">No changes have been made with WinKit on this PC.</li>' }

    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>System report</title>
<style>
  :root { --bg:#f6f7fb; --card:#fff; --text:#0f172a; --muted:#64748b; --line:#e2e8f0; --accent:#1d3bd1;
          --good:#16a34a; --info:#0ea5e9; --warning:#d97706; --critical:#dc2626; }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0b1020; --card:#131a2e; --text:#e2e8f0; --muted:#94a3b8; --line:#1f2a44; --accent:#6d8bff; }
  }
  * { box-sizing:border-box }
  body { margin:0; font:15px/1.5 "Segoe UI", system-ui, sans-serif; background:var(--bg); color:var(--text); }
  main { max-width:880px; margin:0 auto; padding:40px 20px 60px; }
  header { display:flex; align-items:center; gap:24px; margin-bottom:28px; flex-wrap:wrap }
  .score { width:112px; height:112px; border-radius:50%; display:grid; place-items:center;
           background:conic-gradient(var(--accent) calc($($Health.Score) * 1%), var(--line) 0); }
  .score div { width:88px; height:88px; border-radius:50%; background:var(--bg); display:grid; place-items:center;
               font-size:30px; font-weight:700 }
  h1 { margin:0; font-size:26px } h2 { font-size:17px; margin:0 0 14px }
  .sub { color:var(--muted); margin:4px 0 0 }
  section { background:var(--card); border:1px solid var(--line); border-radius:14px; padding:22px; margin-bottom:18px }
  table { width:100%; border-collapse:collapse } th, td { text-align:left; padding:8px 0; border-bottom:1px solid var(--line); vertical-align:top }
  th { width:34%; color:var(--muted); font-weight:500 } tr:last-child th, tr:last-child td { border:0 }
  ul { list-style:none; margin:0; padding:0 }
  .checks li { display:flex; gap:12px; align-items:flex-start; padding:10px 0; border-bottom:1px solid var(--line) }
  .checks li:last-child, .changes li:last-child { border:0 }
  .checks p { margin:2px 0 0; color:var(--muted) } .checks div { flex:1 }
  .checks em { font-style:normal; font-size:12px; color:var(--muted) }
  .dot { width:10px; height:10px; border-radius:50%; margin-top:7px; background:var(--muted) }
  .good .dot { background:var(--good) } .info .dot { background:var(--info) }
  .warning .dot { background:var(--warning) } .critical .dot { background:var(--critical) }
  .changes li { padding:8px 0; border-bottom:1px solid var(--line) }
  .changes span { display:inline-block; min-width:150px; color:var(--muted) }
  .empty { color:var(--muted) }
  footer { text-align:center; color:var(--muted); font-size:13px; margin-top:28px }
  footer a { color:var(--accent); text-decoration:none; font-weight:600 }
</style>
</head>
<body>
<main>
  <header>
    <div class="score"><div>$($Health.Score)</div></div>
    <div>
      <h1>$(& $e $Health.Grade)</h1>
      <p class="sub">$(& $e "$($s.Manufacturer) $($s.Model)".Trim()) &middot; checked $(& $e $Health.CheckedAt.ToString('f', $en))</p>
    </div>
  </header>
  <section><h2>System</h2><table>$($rows -join '')</table></section>
  <section><h2>Health checks</h2><ul class="checks">$($checks -join '')</ul></section>
  <section><h2>Changes made with WinKit</h2><ul class="changes">$changes</ul></section>
  <footer>Generated by Klaudik WinKit $(& $e $WK.Version) &middot; <a href="https://klaudik.com">klaudik.com</a></footer>
</main>
</body>
</html>
"@

    [System.IO.File]::WriteAllText($Path, $html, (New-Object System.Text.UTF8Encoding $false))
    Write-WKLog "Report saved to $Path" -Level Success
    return $Path
}
